[package]
name = "coral"
version = "0.1.0"
edition = "2021"
include = ["/src"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
