[package]
name = "coral"
version = "0.1.0"
edition = "2021"
include = ["/src"]

[dependencies]
sdl2 = "0.36.0"

[dev-dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }


[profile.dev]
overflow-checks=false
[profile.release]
overflow-checks=false
